name = "cors"
main = "src/index.ts"
compatibility_date = "2025-04-27"
compatibility_flags = [ "nodejs_compat"]
[[resource_bindings]]
name = "MYBROWSER" # Nama binding yang akan diakses di Worker (env.MYBROWSER)
service = "cloudflare_browser_rendering" # Jenis resource

kv_namespaces = [
  { binding = "BROWSER_KV_DEMO", id = "a3c8b75571bb46598a07ea7dd7ed07db", preview_id = "e7c760c37afd4d469513287e1233179c" }
]
