name = "rendering-api-demo"
main = "src/index.ts"
compatibility_date = "2025-04-27"
compatibility_flags = [ "nodejs_compat"]
browser = { binding = "MYBROWSER" }
kv_namespaces = [
  { binding = "BROWSER_KV_DEMO", id = "e0d5018ed3ba9c871888bb16b8aab58a", preview_id = "e1f8b68b68d24381b57071445f96e623" }
]
